#
# Copyright (c) 2014-2019 - UPMEM
#

set(DPU_HOST_LIBRARIES dpu)
get_filename_component(DPU_HOST_PACKAGE_DIR ${CMAKE_CURRENT_LIST_DIR}/../../../../../ ABSOLUTE)
set(DPU_HOST_INCLUDE_DIRECTORIES ${DPU_HOST_PACKAGE_DIR}/include/dpu)
set(DPU_HOST_LINK_DIRECTORIES ${DPU_HOST_PACKAGE_DIR}/lib)
