#ifndef __CROS_EC_FLASH_PARTITION_H
#define __CROS_EC_FLASH_PARTITION_H

#define FLASH_BASE_ADDRESS 0x08000000
#define FLASH_SIZE 0x20000

#define FLASH_OFF_RO 0x0
#define FLASH_OFF_RW 0xF000
#define FLASH_OFF_VPD 0x1E000
#define FLASH_OFF_VPD_DB 0x1E800
#define FLASH_OFF_SPD 0x1F800

/* For now, RO and RW partitions are of the same size */
#define FLASH_SIZE_RO_RW (FLASH_OFF_VPD - FLASH_OFF_RO)
#define FLASH_SIZE_RO (FLASH_OFF_RW - FLASH_OFF_RO)
#define FLASH_SIZE_RW (FLASH_OFF_VPD - FLASH_OFF_RW)
#define FLASH_SIZE_VPD (FLASH_OFF_VPD_DB - FLASH_OFF_VPD)
#define FLASH_SIZE_VPD_DB (FLASH_OFF_SPD - FLASH_OFF_VPD_DB)
#define FLASH_SIZE_SPD (FLASH_SIZE - FLASH_OFF_SPD)

#endif /* __CROS_EC_FLASH_PARTITION_H */
